name: quickbuild-windows

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # for quickly testing patches over any previous partbuild
  quickwindows:
      runs-on: windows-latest
      env:
        VMAJOR: 140
        VERSION: 140.0.7339.208
        SRCDIR: chromium-src
        DEPOT_TOOLS_WIN_TOOLCHAIN: 0
        MSYS: winsymlinks:native
      steps:
      - name: Download source tarball
        uses: actions/download-artifact@v4
        with:
          name: windows-src-${{ env.VERSION }}
          path: ${{ github.workspace }}\chromium-src
          github-token: ${{ secrets.PAT }}
          run-id: 17165507192

      - name: Download out directory
        uses: actions/download-artifact@v4
        with:
          name: chromium-out-${{ env.VERSION }}
          path: ${{ github.workspace }}\chromium-src
          github-token: ${{ secrets.PAT }}
          run-id: 17165507192

      - name: Download versioned branding patches
        uses: actions/download-artifact@v4
        with:
          name: windows-patch-${{ env.VERSION }}
          path: ${{ github.workspace }}\chromium-src
          github-token: ${{ secrets.PAT }}
          run-id: 17165507192

      - uses: actions/checkout@v4
        with:
          repository: 'COD3HUNT3R/desktop'
          path: 'chromium-src/desktop'
          token: ${{ secrets.PAT }}

      - uses: actions/checkout@v4
        with:
          repository: 'COD3HUNT3R/extensions'
          path: 'chromium-src/extensions'
          token: ${{ secrets.PAT }}

      - uses: actions/checkout@v4
        with:
          repository: 'COD3HUNT3R/patches'
          path: 'chromium-src/patches'
          token: ${{ secrets.PAT }}

      - name: Clone depot_tools
        shell: bash
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: |
          cd ${{ env.SRCDIR }}
          git config --global depot-tools.allowGlobalGitConfig true
          echo "Clone depot_tools..."
          git clone --depth=1 https://chromium.googlesource.com/chromium/tools/depot_tools
          echo "::add-path::$GITHUB_WORKSPACE/chromium-src/depot_tools"

      - name: Extract tar
        shell: bash
        run: |
          cd ${{ env.SRCDIR }} && ls
          tar -xf chromium-$VERSION.tar.xz
          tar -xf out.tar.zst
          ls -lsh
          rm -f chromium-$VERSION.tar.xz out.tar.zst
          mv out chromium-$VERSION && cd chromium-$VERSION
          patch -p1 < ../kingdom$VMAJOR-$VERSION-branding.patch
          patch -p1 < ../patches/kingdom/$VMAJOR/common/kingdom$VMAJOR-component-update-url.patch
          patch -p1 < ../patches/kingdom/$VMAJOR/common/kingdom$VMAJOR-time-server.patch
          patch -p1 < ../patches/kingdom/$VMAJOR/common/kingdom$VMAJOR-domain-reliability.patch
          patch -p1 < ../patches/kingdom/$VMAJOR/common/kingdom$VMAJOR-root-store.patch
          patch -p1 < ../patches/kingdom/$VMAJOR/common/kingdom$VMAJOR-banned-tld.patch
          patch -p1 < ../patches/kingdom/$VMAJOR/common/kingdom$VMAJOR-kingdom-dns.patch
          patch -p1 < ../patches/kingdom/$VMAJOR/common/kingdom$VMAJOR-notrash-component-extension.patch
          patch -p1 < ../patches/kingdom/$VMAJOR/common/kingdom$VMAJOR-gaia-to-baia.patch
          patch -p1 < ../patches/kingdom/$VMAJOR/desktop/kingdom$VMAJOR-kingdom-safe-browsing.patch
          patch -p1 < ../patches/kingdom/$VMAJOR/desktop/kingdom$VMAJOR-browser-feedback.patch
          patch -p1 < ../patches/kingdom/$VMAJOR/desktop/kingdom$VMAJOR-extensions-manifestv2.patch
          patch -p1 < ../patches/kingdom/$VMAJOR/desktop/kingdom$VMAJOR-opera-addons-extension-store.patch
          patch -p1 < ../patches/kingdom/$VMAJOR/desktop/kingdom$VMAJOR-pin-extension-beside-omnibar.patch
          patch -p1 < ../patches/kingdom/$VMAJOR/desktop/kingdom$VMAJOR-porda-ai-extension-and-kahf-doh-server.patch
          patch -p1 < ../patches/kingdom/$VMAJOR/windows/kingdom$VMAJOR-windows-install-directory-constants.patch
          #patch -p1 < ../patches/kingdom/$VMAJOR/windows/kingdom$VMAJOR-windows-updater.patch
          cp -rf ../desktop/kingdom/chrome .
          cp -rf ../desktop/kingdom/components .
          cp -rf ../desktop/kingdom/ui .
          cp -rf ../extensions/kingdom/chrome .
          pwd && ls -lsh chrome/app/theme/chromium

      - name: Build chrome
        shell: bash
        run: |
          cd ${{ env.SRCDIR }}/chromium-${{ env.VERSION }}
          ninja -j 4 -C out/release chrome

      - name: Build chromedriver
        shell: bash
        run: |
          cd ${{ env.SRCDIR }}/chromium-${{ env.VERSION }}
          ninja -j 4 -C out/release chromedriver

      - name: Build installer & mini_installer
        shell: bash
        run: |
          cd ${{ env.SRCDIR }}/chromium-${{ env.VERSION }}
          ninja -j 4 -C out/release installer
          ninja -j 4 -C out/release mini_installer
          mv out/release/mini_installer.exe out/release/kingdom-browser.exe
          ls out/release

      - name: Upload windows packages
        uses: actions/upload-artifact@v4
        with:
          name: packages-kingdom-windows-${{ env.VERSION }}
          path: ${{ github.workspace }}\chromium-src\chromium-${{ env.VERSION }}\out\release\kingdom-browser.exe

      - name: Compress artifacts
        shell: bash
        run: |
          cd ${{ env.SRCDIR }}/chromium-$VERSION
          ZSTD_CLEVEL=12 tar -I zstd --force-local -cvpf D:/a/laddu/laddu/chromium-src/out.tar.zst ./out

      - name: Upload out directory
        uses: actions/upload-artifact@v4
        with:
          name: chromium-out-${{ env.VERSION }}
          path: ${{ github.workspace }}\chromium-src\out.tar.zst
          overwrite: true
